import type { Metadata } from "next";
import '@/app/globals.css'
import { Outfit } from "next/font/google";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";
import { ProductProvider } from "./context/ProductContext";
import { ClerkProvider } from '@clerk/nextjs'
import { Analytics } from '@vercel/analytics/next';

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TechD",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await fetch('https://dummyjson.com/products/category/smartphones')
  const data = await res.json()

  return (
    <ClerkProvider>
      <html lang="en">
        <ProductProvider initialProducts={data.products}>
          <body
            className={`${outfit.className}`}
          >
            <Navbar />
            <section className="container justify-center mx-auto min-h-screen">
              {children}
            </section> 
            <Footer />
            <Analytics />
          </body>
        </ProductProvider>
      </html>
    </ClerkProvider>
  );
}
